
import { CurriculumCompetency } from './types';

export const LP21_AREAS = [
    'Sprachen',
    'Mathematik',
    'Natur, Mensch, Gesellschaft (NMG)',
    'Gestalten',
    'Musik',
    'Bewegung und Sport',
    'Medien und Informatik',
];

export const LP21_CYCLES = ['Zyklus 1', 'Zyklus 2', 'Zyklus 3'];

export const LP21_COMPETENCIES: CurriculumCompetency[] = [
    // ─── Sprachen: Deutsch ──────────────────────────────────────────────────────────
    {
        id: 'd-1-a-1',
        code: 'D.1.A.1',
        area: 'Sprachen',
        competencyArea: 'Hören',
        competency: 'Die Schülerinnen und Schüler können Gesprächen folgen und die Aufmerksamkeit auf Sprechende richten.',
        cycle: 'Zyklus 1',
        levelIndicators: ['Können Blickkontakt halten', 'Können kurze Anweisungen befolgen'],
    },
    {
        id: 'd-1-b-1',
        code: 'D.1.B.1',
        area: 'Sprachen',
        competencyArea: 'Hören',
        competency: 'Die Schülerinnen und Schüler können wichtige Informationen aus Hörtexten entnehmen.',
        cycle: 'Zyklus 2',
        levelIndicators: ['Können Schlüsselwörter notieren', 'Können Fragen zum Gehörten beantworten'],
    },
    {
        id: 'd-1-c-1',
        code: 'D.1.C.1',
        area: 'Sprachen',
        competencyArea: 'Hören',
        competency: 'Die Schülerinnen und Schüler können Hörtexte und Redebeiträge kritisch analysieren.',
        cycle: 'Zyklus 3',
        levelIndicators: ['Argumentation in Debatten verfolgen', 'Manipulative Strategien erkennen'],
    },
    {
        id: 'd-2-a-1',
        code: 'D.2.A.1',
        area: 'Sprachen',
        competencyArea: 'Lesen',
        competency: 'Die Schülerinnen und Schüler können Wörter und kurze Sätze lesen und verstehen.',
        cycle: 'Zyklus 1',
        levelIndicators: ['Buchstaben-Laut-Zuordnung beherrschen', 'Einfache Bilderbücher lesen'],
    },
    {
        id: 'd-2-b-1',
        code: 'D.2.B.1',
        area: 'Sprachen',
        competencyArea: 'Lesen',
        competency: 'Die Schülerinnen und Schüler verstehen Sachtexte, literarische Texte und nichtlineare Texte.',
        cycle: 'Zyklus 2',
        levelIndicators: ['Können den roten Faden erkennen', 'Unbekannte Wörter erschliessen'],
    },
    {
        id: 'd-2-c-1',
        code: 'D.2.C.1',
        area: 'Sprachen',
        competencyArea: 'Lesen',
        competency: 'Die Schülerinnen und Schüler können das Leseverstehen überprüfen.',
        cycle: 'Zyklus 3',
        levelIndicators: ['Überwachen ihr Verständnis selbstständig', 'Nutzen Nachschlagewerke'],
    },
    {
        id: 'd-3-a-1',
        code: 'D.3.A.1',
        area: 'Sprachen',
        competencyArea: 'Sprechen',
        competency: 'Die Schülerinnen und Schüler können sich in monologischen Situationen ausdrücken.',
        cycle: 'Zyklus 1',
        levelIndicators: ['Können ein Erlebnis erzählen', 'Können ein Bild beschreiben'],
    },
    {
        id: 'd-3-b-1',
        code: 'D.3.B.1',
        area: 'Sprachen',
        competencyArea: 'Sprechen',
        competency: 'Die Schülerinnen und Schüler können sich an Gesprächen beteiligen und Dialogregeln einhalten.',
        cycle: 'Zyklus 2',
        levelIndicators: ['Ausreden lassen', 'Auf Beiträge anderer eingehen', 'Meinung begründen'],
    },
    {
        id: 'd-3-c-1',
        code: 'D.3.C.1',
        area: 'Sprachen',
        competencyArea: 'Sprechen',
        competency: 'Die Schülerinnen und Schüler können Kurzpräsentationen vorbereiten und durchführen.',
        cycle: 'Zyklus 3',
        levelIndicators: ['Strukturiert präsentieren', 'Medien gezielt einsetzen', 'Auf Rückfragen eingehen'],
    },
    {
        id: 'd-4-a-1',
        code: 'D.4.A.1',
        area: 'Sprachen',
        competencyArea: 'Schreiben',
        competency: 'Die Schülerinnen und Schüler können Grundfertigkeiten des Schreibens erwerben.',
        cycle: 'Zyklus 1',
        levelIndicators: ['Kennen die Buchstabenformen', 'Schreiben lautgetreu'],
    },
    {
        id: 'd-4-d-1',
        code: 'D.4.D.1',
        area: 'Sprachen',
        competencyArea: 'Schreiben',
        competency: 'Die Schülerinnen und Schüler können Texte verfassen.',
        cycle: 'Zyklus 2',
        levelIndicators: ['Können eine Geschichte logisch aufbauen', 'Verwenden abwechslungsreiche Satzanfänge'],
    },
    {
        id: 'd-4-f-1',
        code: 'D.4.F.1',
        area: 'Sprachen',
        competencyArea: 'Schreiben',
        competency: 'Die Schülerinnen und Schüler können Texte überarbeiten.',
        cycle: 'Zyklus 3',
        levelIndicators: ['Nutzen Feedback von anderen', 'Korrigieren Rechtschreibung und Grammatik'],
    },
    {
        id: 'd-5-a-1',
        code: 'D.5.A.1',
        area: 'Sprachen',
        competencyArea: 'Sprache im Fokus',
        competency: 'Die Schülerinnen und Schüler können Wortarten bestimmen und deren Funktion im Satz erkennen.',
        cycle: 'Zyklus 2',
        levelIndicators: ['Nomen, Verben, Adjektive erkennen', 'Singular/Plural bilden'],
    },
    {
        id: 'd-5-b-1',
        code: 'D.5.B.1',
        area: 'Sprachen',
        competencyArea: 'Sprache im Fokus',
        competency: 'Die Schülerinnen und Schüler können grammatische Strukturen analysieren und anwenden.',
        cycle: 'Zyklus 3',
        levelIndicators: ['Satzglieder bestimmen', 'Zeitformen korrekt verwenden', 'Konjunktiv erkennen'],
    },
    {
        id: 'd-6-a-1',
        code: 'D.6.A.1',
        area: 'Sprachen',
        competencyArea: 'Literatur im Fokus',
        competency: 'Die Schülerinnen und Schüler können literarische Texte lesen und sich mit ihnen auseinandersetzen.',
        cycle: 'Zyklus 2',
        levelIndicators: ['Märchen und Fabeln kennen', 'Figuren beschreiben', 'Lieblingsbücher vorstellen'],
    },
    {
        id: 'd-6-b-1',
        code: 'D.6.B.1',
        area: 'Sprachen',
        competencyArea: 'Literatur im Fokus',
        competency: 'Die Schülerinnen und Schüler können literarische Texte interpretieren und Bezüge herstellen.',
        cycle: 'Zyklus 3',
        levelIndicators: ['Erzählperspektive erkennen', 'Themen und Motive analysieren', 'Literarische Epochen zuordnen'],
    },

    // ─── Sprachen: Fremdsprachen (E/F) ──────────────────────────────────────────────
    {
        id: 'fs-1-a-1',
        code: 'FS1.A.1',
        area: 'Sprachen',
        competencyArea: 'Hören (Fremdsprache)',
        competency: 'Die Schülerinnen und Schüler können vertraute Wörter und ganz einfache Sätze verstehen.',
        cycle: 'Zyklus 2',
        levelIndicators: ['Verstehen einfache Begrüssungen', 'Können Zahlen und Farben zuordnen'],
    },
    {
        id: 'fs-1-b-1',
        code: 'FS1.B.1',
        area: 'Sprachen',
        competencyArea: 'Lesen (Fremdsprache)',
        competency: 'Die Schülerinnen und Schüler können kurze, einfache Texte in der Fremdsprache lesen.',
        cycle: 'Zyklus 2',
        levelIndicators: ['Einfache Schilder und Beschriftungen verstehen', 'Kurze Mitteilungen lesen'],
    },
    {
        id: 'fs-2-a-1',
        code: 'FS2.A.1',
        area: 'Sprachen',
        competencyArea: 'Sprechen (Fremdsprache)',
        competency: 'Die Schülerinnen und Schüler können sich in vertrauten Situationen verständigen.',
        cycle: 'Zyklus 3',
        levelIndicators: ['Können nach dem Weg fragen', 'Können im Restaurant bestellen'],
    },
    {
        id: 'fs-2-b-1',
        code: 'FS2.B.1',
        area: 'Sprachen',
        competencyArea: 'Schreiben (Fremdsprache)',
        competency: 'Die Schülerinnen und Schüler können kurze Texte in der Fremdsprache verfassen.',
        cycle: 'Zyklus 3',
        levelIndicators: ['E-Mails und Postkarten schreiben', 'Über sich selbst berichten'],
    },

    // ─── Mathematik ─────────────────────────────────────────────────────────────────
    {
        id: 'ma-1-a-1',
        code: 'MA.1.A.1',
        area: 'Mathematik',
        competencyArea: 'Zahl und Variable',
        competency: 'Die Schülerinnen und Schüler verstehen und verwenden arithmetische Begriffe und Symbole.',
        cycle: 'Zyklus 1',
        levelIndicators: ['Zahlen bis 20 lesen und schreiben', 'Rechenzeichen + und - verstehen'],
    },
    {
        id: 'ma-1-a-2',
        code: 'MA.1.A.2',
        area: 'Mathematik',
        competencyArea: 'Zahl und Variable',
        competency: 'Die Schülerinnen und Schüler können zählen, ordnen und vergleichen.',
        cycle: 'Zyklus 1',
        levelIndicators: ['Vorwärts und rückwärts zählen', 'Mengen vergleichen'],
    },
    {
        id: 'ma-1-a-3',
        code: 'MA.1.A.3',
        area: 'Mathematik',
        competencyArea: 'Zahl und Variable',
        competency: 'Die Schülerinnen und Schüler können im Dezimalsystem addieren und subtrahieren.',
        cycle: 'Zyklus 2',
        levelIndicators: ['Schriftlich addieren bis 1000', 'Einmaleins automatisiert beherrschen'],
    },
    {
        id: 'ma-1-b-1',
        code: 'MA.1.B.1',
        area: 'Mathematik',
        competencyArea: 'Zahl und Variable',
        competency: 'Die Schülerinnen und Schüler können Brüche, Dezimalbrüche und Prozente verstehen und anwenden.',
        cycle: 'Zyklus 2',
        levelIndicators: ['Brüche als Teile eines Ganzen darstellen', 'Einfache Brüche vergleichen und ordnen'],
    },
    {
        id: 'ma-1-b-2',
        code: 'MA.1.B.2',
        area: 'Mathematik',
        competencyArea: 'Zahl und Variable',
        competency: 'Die Schülerinnen und Schüler können Bruchoperationen ausführen und Brüche in Dezimalzahlen umwandeln.',
        cycle: 'Zyklus 3',
        levelIndicators: ['Brüche addieren, subtrahieren, multiplizieren', 'Prozentrechnung anwenden'],
    },
    {
        id: 'ma-1-c-1',
        code: 'MA.1.C.1',
        area: 'Mathematik',
        competencyArea: 'Zahl und Variable',
        competency: 'Die Schülerinnen und Schüler können Terme umformen und Gleichungen lösen.',
        cycle: 'Zyklus 3',
        levelIndicators: ['Lineare Gleichungen lösen', 'Klammerregeln anwenden'],
    },
    {
        id: 'ma-1-d-1',
        code: 'MA.1.D.1',
        area: 'Mathematik',
        competencyArea: 'Zahl und Variable',
        competency: 'Die Schülerinnen und Schüler können multiplizieren und dividieren.',
        cycle: 'Zyklus 2',
        levelIndicators: ['Einmaleins-Reihen beherrschen', 'Schriftliche Division durchführen'],
    },
    {
        id: 'ma-2-a-1',
        code: 'MA.2.A.1',
        area: 'Mathematik',
        competencyArea: 'Form und Raum',
        competency: 'Die Schülerinnen und Schüler können Figuren und Körper abbilden, zerlegen und zusammensetzen.',
        cycle: 'Zyklus 2',
        levelIndicators: ['Symmetrien erkennen', 'Würfelnetze zeichnen'],
    },
    {
        id: 'ma-2-a-2',
        code: 'MA.2.A.2',
        area: 'Mathematik',
        competencyArea: 'Form und Raum',
        competency: 'Die Schülerinnen und Schüler können geometrische Formen erkennen und benennen.',
        cycle: 'Zyklus 1',
        levelIndicators: ['Kreis, Dreieck, Rechteck unterscheiden', 'Formen im Alltag finden'],
    },
    {
        id: 'ma-2-b-1',
        code: 'MA.2.B.1',
        area: 'Mathematik',
        competencyArea: 'Form und Raum',
        competency: 'Die Schülerinnen und Schüler können Längen, Flächen und Volumen bestimmen.',
        cycle: 'Zyklus 3',
        levelIndicators: ['Satz des Pythagoras anwenden', 'Kreisfläche berechnen'],
    },
    {
        id: 'ma-2-c-1',
        code: 'MA.2.C.1',
        area: 'Mathematik',
        competencyArea: 'Form und Raum',
        competency: 'Die Schülerinnen und Schüler können Koordinaten im Zahlenstrahl und in der Ebene verwenden.',
        cycle: 'Zyklus 3',
        levelIndicators: ['Punkte im Koordinatensystem ablesen', 'Figuren verschieben und spiegeln'],
    },
    {
        id: 'ma-3-a-1',
        code: 'MA.3.A.1',
        area: 'Mathematik',
        competencyArea: 'Grössen, Funktionen, Daten',
        competency: 'Die Schülerinnen und Schüler können Grössen schätzen, messen und umwandeln.',
        cycle: 'Zyklus 2',
        levelIndicators: ['Geld, Gewicht, Zeit umrechnen', 'Sachaufgaben mit Grössen lösen'],
    },
    {
        id: 'ma-3-b-1',
        code: 'MA.3.B.1',
        area: 'Mathematik',
        competencyArea: 'Grössen, Funktionen, Daten',
        competency: 'Die Schülerinnen und Schüler können Daten sammeln, ordnen und darstellen.',
        cycle: 'Zyklus 2',
        levelIndicators: ['Strichlisten und einfache Diagramme erstellen', 'Daten ablesen und interpretieren'],
    },
    {
        id: 'ma-3-b-2',
        code: 'MA.3.B.2',
        area: 'Mathematik',
        competencyArea: 'Grössen, Funktionen, Daten',
        competency: 'Die Schülerinnen und Schüler können Wahrscheinlichkeiten abschätzen und berechnen.',
        cycle: 'Zyklus 3',
        levelIndicators: ['Zufallsexperimente durchführen', 'Wahrscheinlichkeiten als Bruch/Prozent angeben'],
    },
    {
        id: 'ma-3-c-1',
        code: 'MA.3.C.1',
        area: 'Mathematik',
        competencyArea: 'Grössen, Funktionen, Daten',
        competency: 'Die Schülerinnen und Schüler können proportionale und lineare Zusammenhänge beschreiben.',
        cycle: 'Zyklus 3',
        levelIndicators: ['Funktionsgraphen interpretieren', 'Dreisatz sicher anwenden'],
    },

    // ─── NMG ────────────────────────────────────────────────────────────────────────
    {
        id: 'nmg-1-1',
        code: 'NMG.1.1',
        area: 'Natur, Mensch, Gesellschaft (NMG)',
        competencyArea: 'Identität, Körper, Gesundheit',
        competency: 'Die Schülerinnen und Schüler können sich und andere wahrnehmen und beschreiben.',
        cycle: 'Zyklus 1',
        levelIndicators: ['Körperteile benennen', 'Gefühle ausdrücken'],
    },
    {
        id: 'nmg-1-2',
        code: 'NMG.1.2',
        area: 'Natur, Mensch, Gesellschaft (NMG)',
        competencyArea: 'Identität, Körper, Gesundheit',
        competency: 'Die Schülerinnen und Schüler können Zusammenhänge von Ernährung und Wohlbefinden erkennen.',
        cycle: 'Zyklus 1',
        levelIndicators: ['Gesunde und ungesunde Lebensmittel unterscheiden', 'Essgewohnheiten reflektieren'],
    },
    {
        id: 'nmg-2-1',
        code: 'NMG.2.1',
        area: 'Natur, Mensch, Gesellschaft (NMG)',
        competencyArea: 'Tiere, Pflanzen und Lebensräume',
        competency: 'Die Schülerinnen und Schüler können Tiere und Pflanzen in ihren Lebensräumen erkunden.',
        cycle: 'Zyklus 2',
        levelIndicators: ['Einheimische Bäume bestimmen', 'Lebensweise von Waldtieren beschreiben'],
    },
    {
        id: 'nmg-2-2',
        code: 'NMG.2.2',
        area: 'Natur, Mensch, Gesellschaft (NMG)',
        competencyArea: 'Tiere, Pflanzen und Lebensräume',
        competency: 'Die Schülerinnen und Schüler können Wachstum, Vermehrung und Entwicklung von Lebewesen verstehen.',
        cycle: 'Zyklus 2',
        levelIndicators: ['Lebenszyklus einer Pflanze beschreiben', 'Metamorphose z.B. Frosch erklären'],
    },
    {
        id: 'nmg-3-1',
        code: 'NMG.3.1',
        area: 'Natur, Mensch, Gesellschaft (NMG)',
        competencyArea: 'Stoffe, Energie und Bewegungen',
        competency: 'Die Schülerinnen und Schüler können Stoffeigenschaften untersuchen.',
        cycle: 'Zyklus 2',
        levelIndicators: ['Schwimmfähigkeit testen', 'Magnetismus erforschen'],
    },
    {
        id: 'nmg-3-2',
        code: 'NMG.3.2',
        area: 'Natur, Mensch, Gesellschaft (NMG)',
        competencyArea: 'Stoffe, Energie und Bewegungen',
        competency: 'Die Schülerinnen und Schüler können verschiedene Energieformen und -quellen untersuchen.',
        cycle: 'Zyklus 2',
        levelIndicators: ['Stromkreis bauen', 'Erneuerbare vs. fossile Energie unterscheiden'],
    },
    {
        id: 'nmg-4-1',
        code: 'NMG.4.1',
        area: 'Natur, Mensch, Gesellschaft (NMG)',
        competencyArea: 'Phänomene der belebten und unbelebten Natur',
        competency: 'Die Schülerinnen und Schüler können Wetterphänomene beobachten und messen.',
        cycle: 'Zyklus 2',
        levelIndicators: ['Thermometer ablesen', 'Wolkenarten unterscheiden'],
    },
    {
        id: 'nmg-5-1',
        code: 'NMG.5.1',
        area: 'Natur, Mensch, Gesellschaft (NMG)',
        competencyArea: 'Technische Entwicklungen / Arbeit',
        competency: 'Die Schülerinnen und Schüler können technische Alltagsgeräte untersuchen und deren Funktion verstehen.',
        cycle: 'Zyklus 1',
        levelIndicators: ['Einfache Mechanismen erkunden (Hebel, Rolle)', 'Werkzeuge sachgerecht einsetzen'],
    },
    {
        id: 'nmg-6-1',
        code: 'NMG.6.1',
        area: 'Natur, Mensch, Gesellschaft (NMG)',
        competencyArea: 'Arbeit, Produktion, Konsum',
        competency: 'Die Schülerinnen und Schüler können den Weg von Gütern vom Rohstoff zum Produkt nachvollziehen.',
        cycle: 'Zyklus 2',
        levelIndicators: ['Produktionsketten beschreiben', 'Herkunft von Lebensmitteln erkunden'],
    },
    {
        id: 'nmg-7-1',
        code: 'NMG.7.1',
        area: 'Natur, Mensch, Gesellschaft (NMG)',
        competencyArea: 'Lebensweisen und Gesellschaft',
        competency: 'Die Schülerinnen und Schüler können unterschiedliche Lebensweisen und Kulturen erkunden.',
        cycle: 'Zyklus 2',
        levelIndicators: ['Feste und Traditionen vergleichen', 'Gemeinsamkeiten und Unterschiede benennen'],
    },
    {
        id: 'nmg-10-1',
        code: 'NMG.10.1',
        area: 'Natur, Mensch, Gesellschaft (NMG)',
        competencyArea: 'Gemeinschaft und Zusammenleben',
        competency: 'Die Schülerinnen und Schüler können Regeln und deren Bedeutung für das Zusammenleben reflektieren.',
        cycle: 'Zyklus 1',
        levelIndicators: ['Klassenregeln mitgestalten', 'Fairness und Gerechtigkeit einschätzen'],
    },
    {
        id: 'nmg-10-2',
        code: 'NMG.10.2',
        area: 'Natur, Mensch, Gesellschaft (NMG)',
        competencyArea: 'Gemeinschaft und Zusammenleben',
        competency: 'Die Schülerinnen und Schüler können Konflikte einordnen und konstruktive Lösungen suchen.',
        cycle: 'Zyklus 2',
        levelIndicators: ['Ich-Botschaften formulieren', 'Mediation kennenlernen'],
    },
    {
        id: 'rzg-1-1',
        code: 'RZG.1.1',
        area: 'Natur, Mensch, Gesellschaft (NMG)',
        competencyArea: 'Räume, Zeiten, Gesellschaften',
        competency: 'Die Schülerinnen und Schüler können sich im Raum orientieren.',
        cycle: 'Zyklus 3',
        levelIndicators: ['Karten lesen und interpretieren', 'Topografisches Wissen anwenden'],
    },
    {
        id: 'rzg-5-1',
        code: 'RZG.5.1',
        area: 'Natur, Mensch, Gesellschaft (NMG)',
        competencyArea: 'Schweizer Geschichte',
        competency: 'Die Schülerinnen und Schüler können Entstehung und Entwicklung der Schweiz einordnen.',
        cycle: 'Zyklus 3',
        levelIndicators: ['Bundesbrief und Alte Eidgenossenschaft kennen', 'Bundesstaat 1848 erklären'],
    },
    {
        id: 'rzg-8-1',
        code: 'RZG.8.1',
        area: 'Natur, Mensch, Gesellschaft (NMG)',
        competencyArea: 'Demokratie und Menschenrechte',
        competency: 'Die Schülerinnen und Schüler können das politische System der Schweiz erklären und mitgestalten.',
        cycle: 'Zyklus 3',
        levelIndicators: ['Initiative und Referendum erklären', 'Gewaltenteilung verstehen', 'Abstimmungsvorlagen analysieren'],
    },
    {
        id: 'rzg-8-2',
        code: 'RZG.8.2',
        area: 'Natur, Mensch, Gesellschaft (NMG)',
        competencyArea: 'Demokratie und Menschenrechte',
        competency: 'Die Schülerinnen und Schüler können Menschenrechte kennen und deren Bedeutung reflektieren.',
        cycle: 'Zyklus 3',
        levelIndicators: ['Grundrechte benennen', 'Kinderrechte kennen', 'Historischen Kontext verstehen'],
    },
    {
        id: 'nt-1-1',
        code: 'NT.1.1',
        area: 'Natur, Mensch, Gesellschaft (NMG)',
        competencyArea: 'Natur und Technik',
        competency: 'Die Schülerinnen und Schüler können mikroskopische Strukturen untersuchen.',
        cycle: 'Zyklus 3',
        levelIndicators: ['Mikroskop bedienen', 'Zellen zeichnen'],
    },
    {
        id: 'nt-3-1',
        code: 'NT.3.1',
        area: 'Natur, Mensch, Gesellschaft (NMG)',
        competencyArea: 'Ökosysteme',
        competency: 'Die Schülerinnen und Schüler können Ökosysteme und deren Wechselwirkungen beschreiben.',
        cycle: 'Zyklus 3',
        levelIndicators: ['Nahrungsketten und -netze darstellen', 'Stoffkreisläufe erklären'],
    },
    {
        id: 'nt-4-1',
        code: 'NT.4.1',
        area: 'Natur, Mensch, Gesellschaft (NMG)',
        competencyArea: 'Sinne und Wahrnehmung',
        competency: 'Die Schülerinnen und Schüler können die menschlichen Sinnesorgane untersuchen und Wahrnehmungsprozesse beschreiben.',
        cycle: 'Zyklus 3',
        levelIndicators: ['Aufbau des Auges/Ohrs erklären', 'Optische Täuschungen untersuchen'],
    },
    {
        id: 'wah-1-1',
        code: 'WAH.1.1',
        area: 'Natur, Mensch, Gesellschaft (NMG)',
        competencyArea: 'Wirtschaft, Arbeit, Haushalt',
        competency: 'Die Schülerinnen und Schüler können Konsumentscheidungen reflektieren.',
        cycle: 'Zyklus 3',
        levelIndicators: ['Werbestrategien durchschauen', 'Preis-Leistungs-Verhältnis beurteilen'],
    },
    {
        id: 'wah-3-1',
        code: 'WAH.3.1',
        area: 'Natur, Mensch, Gesellschaft (NMG)',
        competencyArea: 'Ernährung und Gesundheit',
        competency: 'Die Schülerinnen und Schüler können Nahrungsmittel und deren Herkunft beurteilen.',
        cycle: 'Zyklus 3',
        levelIndicators: ['Nährstoffe und Lebensmittelgruppen kennen', 'Mahlzeiten ausgewogen zusammenstellen'],
    },
    {
        id: 'erg-1-1',
        code: 'ERG.1.1',
        area: 'Natur, Mensch, Gesellschaft (NMG)',
        competencyArea: 'Ethik, Religionen, Gemeinschaft',
        competency: 'Die Schülerinnen und Schüler können Werte und Normen diskutieren.',
        cycle: 'Zyklus 3',
        levelIndicators: ['Ethische Dilemmata besprechen', 'Religiöse Traditionen kennenlernen'],
    },
    {
        id: 'erg-5-1',
        code: 'ERG.5.1',
        area: 'Natur, Mensch, Gesellschaft (NMG)',
        competencyArea: 'Zusammenleben und Verantwortung',
        competency: 'Die Schülerinnen und Schüler können Verantwortung für sich und andere übernehmen.',
        cycle: 'Zyklus 3',
        levelIndicators: ['Eigene Stärken und Schwächen reflektieren', 'Zivilcourage zeigen'],
    },

    // ─── Gestalten ──────────────────────────────────────────────────────────────────
    {
        id: 'bg-1-a-1',
        code: 'BG.1.A.1',
        area: 'Gestalten',
        competencyArea: 'Bildnerisches Gestalten',
        competency: 'Die Schülerinnen und Schüler können eigenständig Bildideen entwickeln.',
        cycle: 'Zyklus 2',
        levelIndicators: ['Skizzenbuch führen', 'Experimentieren mit Farben'],
    },
    {
        id: 'bg-1-b-1',
        code: 'BG.1.B.1',
        area: 'Gestalten',
        competencyArea: 'Bildnerisches Gestalten',
        competency: 'Die Schülerinnen und Schüler können Farben wahrnehmen, mischen und gezielt einsetzen.',
        cycle: 'Zyklus 1',
        levelIndicators: ['Grundfarben mischen', 'Warme und kalte Farben unterscheiden'],
    },
    {
        id: 'bg-2-a-1',
        code: 'BG.2.A.1',
        area: 'Gestalten',
        competencyArea: 'Bildnerisches Gestalten',
        competency: 'Die Schülerinnen und Schüler können Verfahren und Materialien gezielt einsetzen.',
        cycle: 'Zyklus 3',
        levelIndicators: ['Drucktechniken anwenden', 'Proportionen zeichnerisch erfassen'],
    },
    {
        id: 'bg-3-a-1',
        code: 'BG.3.A.1',
        area: 'Gestalten',
        competencyArea: 'Bildnerisches Gestalten',
        competency: 'Die Schülerinnen und Schüler können Bilder betrachten, beschreiben und kontextualisieren.',
        cycle: 'Zyklus 3',
        levelIndicators: ['Kunstwerke analysieren', 'Stilrichtungen einordnen', 'Eigene Werke reflektieren'],
    },
    {
        id: 'ttg-1-a-1',
        code: 'TTG.1.A.1',
        area: 'Gestalten',
        competencyArea: 'Textiles und Technisches Gestalten',
        competency: 'Die Schülerinnen und Schüler können Funktion und Konstruktion verstehen.',
        cycle: 'Zyklus 2',
        levelIndicators: ['Einfache Mechanismen bauen', 'Schnittmuster verstehen'],
    },
    {
        id: 'ttg-2-a-1',
        code: 'TTG.2.A.1',
        area: 'Gestalten',
        competencyArea: 'Textiles und Technisches Gestalten',
        competency: 'Die Schülerinnen und Schüler können handwerkliche Verfahren vertiefen.',
        cycle: 'Zyklus 3',
        levelIndicators: ['Sägen und Bohren sicher anwenden', 'Nähmaschine bedienen'],
    },
    {
        id: 'ttg-3-a-1',
        code: 'TTG.3.A.1',
        area: 'Gestalten',
        competencyArea: 'Produktdesign',
        competency: 'Die Schülerinnen und Schüler können ein Produkt von der Idee bis zur Umsetzung planen und gestalten.',
        cycle: 'Zyklus 3',
        levelIndicators: ['Designprozess kennen', 'Prototyp bauen und testen', 'Materialwahl begründen'],
    },

    // ─── Musik ──────────────────────────────────────────────────────────────────────
    {
        id: 'mu-1-a-1',
        code: 'MU.1.A.1',
        area: 'Musik',
        competencyArea: 'Singen und Sprechen',
        competency: 'Die Schülerinnen und Schüler können ihre Stimme vielfältig einsetzen.',
        cycle: 'Zyklus 1',
        levelIndicators: ['Lieder auswendig singen', 'Mit der Stimme experimentieren'],
    },
    {
        id: 'mu-2-a-1',
        code: 'MU.2.A.1',
        area: 'Musik',
        competencyArea: 'Hören und Sich-Orientieren',
        competency: 'Die Schülerinnen und Schüler können Musik bewusst hören und beschreiben.',
        cycle: 'Zyklus 2',
        levelIndicators: ['Instrumente heraushören', 'Musikalische Stimmungen beschreiben'],
    },
    {
        id: 'mu-3-a-1',
        code: 'MU.3.A.1',
        area: 'Musik',
        competencyArea: 'Musizieren',
        competency: 'Die Schülerinnen und Schüler können Instrumente spielen und zusammen musizieren.',
        cycle: 'Zyklus 2',
        levelIndicators: ['Rhythmen auf Perkussionsinstrumenten spielen', 'Einfache Liedbegleitungen spielen'],
    },
    {
        id: 'mu-4-a-1',
        code: 'MU.4.A.1',
        area: 'Musik',
        competencyArea: 'Praxis des musikalischen Wissens',
        competency: 'Die Schülerinnen und Schüler können musikalische Strukturen verstehen.',
        cycle: 'Zyklus 3',
        levelIndicators: ['Noten lesen im Violinschlüssel', 'Rhythmen notieren'],
    },
    {
        id: 'mu-5-a-1',
        code: 'MU.5.A.1',
        area: 'Musik',
        competencyArea: 'Bewegen und Tanzen',
        competency: 'Die Schülerinnen und Schüler können sich zu Musik bewegen und einfache Tanzformen ausführen.',
        cycle: 'Zyklus 1',
        levelIndicators: ['Sich frei zu Musik bewegen', 'Einfache Bewegungsfolgen nachahmen'],
    },

    // ─── Bewegung und Sport ─────────────────────────────────────────────────────────
    {
        id: 'bs-1-a-1',
        code: 'BS.1.A.1',
        area: 'Bewegung und Sport',
        competencyArea: 'Laufen, Springen, Werfen',
        competency: 'Die Schülerinnen und Schüler können Grundformen der Bewegung vielseitig anwenden.',
        cycle: 'Zyklus 1',
        levelIndicators: ['Balancieren', 'Rollen und Drehen'],
    },
    {
        id: 'bs-2-a-1',
        code: 'BS.2.A.1',
        area: 'Bewegung und Sport',
        competencyArea: 'Bewegen an Geräten',
        competency: 'Die Schülerinnen und Schüler können an Geräten sicher turnen.',
        cycle: 'Zyklus 2',
        levelIndicators: ['Klettern und Schwingen', 'Rolle vorwärts / rückwärts'],
    },
    {
        id: 'bs-3-a-1',
        code: 'BS.3.A.1',
        area: 'Bewegung und Sport',
        competencyArea: 'Spielen',
        competency: 'Die Schülerinnen und Schüler können Spielsituationen gemeinsam gestalten.',
        cycle: 'Zyklus 3',
        levelIndicators: ['Teamtaktik anwenden', 'Fairplay-Regeln einhalten'],
    },
    {
        id: 'bs-4-a-1',
        code: 'BS.4.A.1',
        area: 'Bewegung und Sport',
        competencyArea: 'Darstellen und Tanzen',
        competency: 'Die Schülerinnen und Schüler können Bewegungsfolgen und Choreografien gestalten.',
        cycle: 'Zyklus 2',
        levelIndicators: ['Einfache Choreografie erfinden', 'Rhythmisch klatschen und bewegen'],
    },
    {
        id: 'bs-5-a-1',
        code: 'BS.5.A.1',
        area: 'Bewegung und Sport',
        competencyArea: 'Gleiten, Rollen, Fahren',
        competency: 'Die Schülerinnen und Schüler können Gleit-, Roll- und Fahrgeräte sicher nutzen.',
        cycle: 'Zyklus 2',
        levelIndicators: ['Velofahren beherrschen', 'Inline-Skates oder Rollbrett fahren'],
    },

    // ─── Medien und Informatik ──────────────────────────────────────────────────────
    {
        id: 'mi-1-1',
        code: 'MI.1.1',
        area: 'Medien und Informatik',
        competencyArea: 'Medien',
        competency: 'Die Schülerinnen und Schüler können sich in der physischen und medialen Umwelt orientieren.',
        cycle: 'Zyklus 1',
        levelIndicators: ['Medien im Alltag benennen', 'Unterschied Realität/Medien erkennen'],
    },
    {
        id: 'mi-1-2',
        code: 'MI.1.2',
        area: 'Medien und Informatik',
        competencyArea: 'Medien',
        competency: 'Die Schülerinnen und Schüler können Regeln für den sicheren Umgang mit digitalen Medien einhalten.',
        cycle: 'Zyklus 2',
        levelIndicators: ['Passwörter sicher erstellen', 'Persönliche Daten schützen', 'Cybermobbing erkennen'],
    },
    {
        id: 'mi-1-3',
        code: 'MI.1.3',
        area: 'Medien und Informatik',
        competencyArea: 'Medien',
        competency: 'Die Schülerinnen und Schüler können Medien und Medienbeiträge verstehen.',
        cycle: 'Zyklus 2',
        levelIndicators: ['Werbung als solche erkennen', 'Bildsprache untersuchen'],
    },
    {
        id: 'mi-1-4',
        code: 'MI.1.4',
        area: 'Medien und Informatik',
        competencyArea: 'Medienproduktion',
        competency: 'Die Schülerinnen und Schüler können eigene Medienbeiträge gestalten und veröffentlichen.',
        cycle: 'Zyklus 3',
        levelIndicators: ['Videos drehen und schneiden', 'Blog-Beiträge verfassen', 'Urheberrecht beachten'],
    },
    {
        id: 'mi-2-1',
        code: 'MI.2.1',
        area: 'Medien und Informatik',
        competencyArea: 'Informatik',
        competency: 'Die Schülerinnen und Schüler können Daten strukturieren und darstellen.',
        cycle: 'Zyklus 2',
        levelIndicators: ['Baumdiagramme zeichnen', 'Daten in Tabellen ordnen'],
    },
    {
        id: 'mi-2-2',
        code: 'MI.2.2',
        area: 'Medien und Informatik',
        competencyArea: 'Informatik',
        competency: 'Die Schülerinnen und Schüler können Algorithmen verstehen und anwenden.',
        cycle: 'Zyklus 3',
        levelIndicators: ['Einfache Programme schreiben', 'Abläufe mit Schleifen und Bedingungen steuern'],
    },
    {
        id: 'mi-2-3',
        code: 'MI.2.3',
        area: 'Medien und Informatik',
        competencyArea: 'Informatik',
        competency: 'Die Schülerinnen und Schüler verstehen Aufbau und Funktionsweise von Informatiksystemen.',
        cycle: 'Zyklus 3',
        levelIndicators: ['Hardwarekomponenten kennen', 'Netzwerke verstehen'],
    },
];

export function getCompetenciesByArea(area: string): CurriculumCompetency[] {
    return LP21_COMPETENCIES.filter(c => c.area === area);
}

export function getCompetenciesByCycle(cycle: string): CurriculumCompetency[] {
    return LP21_COMPETENCIES.filter(c => c.cycle === cycle);
}

export function getCompetencyById(id: string): CurriculumCompetency | undefined {
    return LP21_COMPETENCIES.find(c => c.id === id);
}
